# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all-devcontainers:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip  # `pip` ecosystem covers `poetry` as well
    directory: "/"
    schedule:
      interval: monthly
    groups:
      all-pip:
        patterns:
          - "*"
