version = 1

[[annotations]]
path = [
    ".devcontainer/*.json",
    ".gitignore",
    "**.lock",
    "REUSE.toml",
    "codecov.yml",
    "pyproject.toml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Public Domain"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".github/**/*.yml",
    "**.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "ANNO DOMINI 2024  Jan Chren ~rindeal  <dev.rindeal gmail com>"
SPDX-License-Identifier = "GPL-3.0-only OR GPL-2.0-only"